language: python

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest coverage pytest-cov
  - pip install codecov black mypy

install:
  - pip install -e . # install package

script:
  - mypy PeptideBuilder/
  - black . --check # check formatting
  - pytest # run tests

after_success:
  - codecov # submit coverage
