language: python

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
  - pip install -e ".[test]" . # install package + test dependencies

script: pytest # run tests

after_success:
  - codecov # submit coverage
