language: python

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U coverage
  - pip install -U pytest-cov
  - pip install codecov

install:
  - pip install -e . # install package

script: pytest # run tests

after_success:
  - codecov # submit coverage
